mode : 'test' # 'run' 'test'

#-------------------
# DATASET
#-------------------
dataset_name : 'Yelp'
n_reviews : 50000 # 'all' or number of first reviews in the dataset

#-------------------
# CRITERIA
#-------------------
criteria : {'Food': ['Food'], 'Price': ['Price'], 'Service': ['Service'], 'Ambiance': ['Ambiance']}
metric : 'cosine' # 'euclidian', 'cosine'

#-------------------
# SENTMENT
#-------------------
sentiment_analyzer : 'NLTK' # 'NLTK' 'TextBlob'

#-------------------
# TESTS
#-------------------
tested_parameter : 'alpha'  # 'theta' 'alpha'
min_value : 0.01
max_value : 5
n_values: 20
significant_digits: 3
loss_type : 'rMSE' # 'MAE' 'rMSE'
stars_averaging : 'weighted' # 'equi' 'weighted'

#-------------------
# RUN
#-------------------
theta : 0   # in [0,1[ 
alpha : 1.3     # in ]0,+inf[
error_max : 1   # in ]0,4[